#!/bin/bash

# Convert IDF binary files to C arrays for embedding in migrator firmware
# Usage: ./convert_bins.sh <bootloader.bin> <partition-table.bin> <app.bin>

set -e

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <bootloader.bin> <partition-table.bin> <app.bin>"
    echo ""
    echo "Example:"
    echo "  $0 ../examples/keepconnect/build/bootloader/bootloader.bin \\"
    echo "     ../examples/keepconnect/build/partition_table/partition-table.bin \\"
    echo "     ../examples/keepconnect/build/smart_outlet.bin"
    exit 1
fi

BOOTLOADER_BIN="$1"
PARTITION_BIN="$2"
APP_BIN="$3"

# Validate files exist
if [ ! -f "$BOOTLOADER_BIN" ]; then
    echo "ERROR: Bootloader binary not found: $BOOTLOADER_BIN"
    exit 1
fi

if [ ! -f "$PARTITION_BIN" ]; then
    echo "ERROR: Partition table binary not found: $PARTITION_BIN"
    exit 1
fi

if [ ! -f "$APP_BIN" ]; then
    echo "ERROR: App binary not found: $APP_BIN"
    exit 1
fi

OUTPUT_FILE="src/idf_binaries.cpp"

echo "Converting binaries to C arrays..."
echo "  Bootloader: $BOOTLOADER_BIN ($(wc -c < "$BOOTLOADER_BIN") bytes)"
echo "  Partition:  $PARTITION_BIN ($(wc -c < "$PARTITION_BIN") bytes)"
echo "  App:        $APP_BIN ($(wc -c < "$APP_BIN") bytes)"
echo ""

# Check app size (max 1600KB = 1638400 bytes)
APP_SIZE=$(wc -c < "$APP_BIN")
MAX_SIZE=1638400  # 1600KB

if [ "$APP_SIZE" -gt "$MAX_SIZE" ]; then
    echo "ERROR: App binary is too large!"
    echo "  Size: $APP_SIZE bytes"
    echo "  Max:  $MAX_SIZE bytes (1600KB)"
    echo "  The app won't fit in the ota_0 partition."
    exit 1
fi

# Generate the C++ file with PROGMEM
cat > "$OUTPUT_FILE" << 'HEADER_END'
#include "idf_binaries.h"

// Auto-generated by convert_bins.sh
// DO NOT EDIT MANUALLY
// Binaries stored in PROGMEM (flash) to save RAM

// BOOTLOADER BINARY
HEADER_END

# Convert bootloader with PROGMEM
echo "const uint8_t bootloader_bin[] PROGMEM = {" >> "$OUTPUT_FILE"
xxd -i < "$BOOTLOADER_BIN" | grep -v "^unsigned" | grep -v "^}" >> "$OUTPUT_FILE"
echo "};" >> "$OUTPUT_FILE"
echo "const size_t bootloader_bin_len = sizeof(bootloader_bin);" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Convert partition table with PROGMEM
echo "// PARTITION TABLE BINARY" >> "$OUTPUT_FILE"
echo "const uint8_t partition_table_bin[] PROGMEM = {" >> "$OUTPUT_FILE"
xxd -i < "$PARTITION_BIN" | grep -v "^unsigned" | grep -v "^}" >> "$OUTPUT_FILE"
echo "};" >> "$OUTPUT_FILE"
echo "const size_t partition_table_bin_len = sizeof(partition_table_bin);" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Convert app - this is the big one, with PROGMEM
echo "// OTA_0 APPLICATION BINARY (HomeKit app)" >> "$OUTPUT_FILE"
echo "const uint8_t ota0_app_bin[] PROGMEM = {" >> "$OUTPUT_FILE"
xxd -i < "$APP_BIN" | grep -v "^unsigned" | grep -v "^}" >> "$OUTPUT_FILE"
echo "};" >> "$OUTPUT_FILE"
echo "const size_t ota0_app_bin_len = sizeof(ota0_app_bin);" >> "$OUTPUT_FILE"

echo "✓ Generated $OUTPUT_FILE"
echo ""
echo "Summary:"
grep "bootloader_bin_len" "$OUTPUT_FILE" | tail -1
grep "partition_table_bin_len" "$OUTPUT_FILE" | tail -1
grep "ota0_app_bin_len" "$OUTPUT_FILE" | tail -1
echo ""
echo "Total embedded size: $(wc -c < "$OUTPUT_FILE") bytes in C++ source"
echo "Binaries stored in PROGMEM (flash, not RAM)"
echo ""
echo "Next steps:"
echo "  1. Build the migrator: cd migrator && pio run"
echo "  2. Test on a single unit first!"
echo "  3. Deploy via your existing KC OTA mechanism"
